name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Edit sources.list
        run: sudo su -c "echo 'deb http://security.ubuntu.com/ubuntu xenial-security main' >> /etc/apt/sources.list"

      - name: Apt update
        run: sudo apt update

      - name: Install libssl1.0.0 for mongod
        run: sudo apt install libssl1.0.0

      - name: Checkout Master
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use Node 14
        uses: actions/setup-node@master
        with:
          node-version: 14

      - name: Get Yarn cache
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Yarn cache
        uses: actions/cache@v4
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-14-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-14-yarn-

      - name: MongoDB Memory Server cache
        uses: actions/cache@v4
        id: mongodb-memory-cache
        with:
          path: .packages/backend/node_modules/.cache/mongodb-memory-server
          key: ${{ runner.os }}-14-mongo-${{ hashFiles('.packages/backend/node_modules/.cache/mongodb-memory-server/mongodb-binaries/*/mongod') }}

      - name: Install dependencies with Yarn
        run: yarn install --ignore-engines

      - name: Test
        run: yarn test
